config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    password: 'secret',
                                    sign_up: 'registration' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'genres#index'

  resources :genres do
    resources :books do
      resources :chapters
      get :upvote, on: :member
    end
    resources :audio_books do
      get :upvote, on: :member
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_book.rb
class AudioBook < ApplicationRecord
  belongs_to :genre
  validates :name, presence: true
  validates :floor, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  has_many   :chapters
  validates :name, presence: true
  validates :floor, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  has_many :audio_books
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:  [:show, :index]
end

app/controllers/audio_books_controller.rb
class AudioBooksController < ApplicationController

  before_action :find_book,  only: [:show, :edit, :update, :destroy, :upvote]
  before_action :find_genre, only: [:index, :edit, :update, :new, :create]

  def index
    @audio_books = AudioBook.where(genre_id: params[:genre_id])
  end

  # /audio_books/1 GET
  def show
  end

  # /audio_books/new GET # в связке с creat
  def new
    @audio_book = AudioBook.new
  end

  # /audio_books/1/edit GET # в связке с update
  def edit
  end

  # /audio_books POST
  def create
    @audio_book = AudioBook.create(book_params)
    if @audio_book.errors.empty?
      redirect_to genre_audio_book_path(@genre, @audio_book)
    else
      render "new"
    end
  end

  # /audio_books/1 PUT
  def update
    @audio_book.update_attributes(book_params)
    if @audio_book.errors.empty?
      redirect_to genre_audio_book_path(@genre, @audio_book)
    else
      render "edit"
    end
  end

  # /audio_books/1 DELETE
  def destroy
    @audio_book.destroy
    redirect_to action: "index"
  end

  def upvote
    @audio_book.increment!(:votes_count)
    redirect_to action: "index"
  end

  private

  def find_genre
    @genre = Genre.find(params[:genre_id])
  end

  def find_book
    @audio_book = AudioBook.find(params[:id])
  end

  def book_params
    params.require(:audio_book).permit(:name, :available, :floor, :quantity, :genre_id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book,  only: [:show, :edit, :update, :destroy, :upvote]
  before_action :find_genre, only: [:index, :edit, :update, :new, :create]

  def index
    @books = Book.where(genre_id: params[:genre_id])
  end

  # /books/1 GET
  def show
  end

  # /books/new GET # в связке с creat
  def new
    @book = Book.new
  end

  # /books/1/edit GET # в связке с update
  def edit
  end

  # /books POST
  def create
    @book = Book.create(book_params.merge(genre_id: @genre.id))
    if @book.errors.empty?
      redirect_to genre_book_path(@genre, @book)
    else
      render "new"
    end
  end

  # /books/1 PUT
  def update
    @book.update_attributes(book_params)
    if @book.errors.empty?
      redirect_to genre_book_path(@genre, @book)
    else
      render "edit"
    end
  end

  # /books/1 DELETE
  def destroy
    @book.destroy
    redirect_to action: "index"
  end

  def upvote
    @book.increment!(:votes_count)
    redirect_to action: "index"
  end

  private

  def find_genre
    @genre = Genre.find(params[:genre_id])
  end

  def find_book
     @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :available, :floor, :quantity, :image)
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_chapter,  only: [:show, :edit, :update, :destroy, :upvote]
  before_action :find_genre,    only: [:index, :edit, :update, :new, :create]
  before_action :find_book,     only: [:index, :edit, :update, :new, :create]

  def index
    @chapters = Chapter.where(genre_id: params[:genre_id], book_id:  params[:book_id])
  end

  # /chapters/1 GET
  def show
  end

  # /chapters/new GET # в связке с creat
  def new
    @chapter = Chapter.new
  end

  # /chapters/1/edit GET # в связке с update
  def edit
  end

  # /chapters POST
  def create
    @chapter = Chapter.create(chapter_params.merge(book_id: @book.id, genre_id: @genre.id))
    if @chapter.errors.empty?
      redirect_to genre_book_chapter_path(@genre, @book, @chapter)
    else
      render "new"
    end
  end

  # /chapters/1 PUT
  def update
    @chapter.update_attributes(chapter_params)
    if @chapter.errors.empty?
      redirect_to genre_book_chapter_path(@genre, @book, @chapter)
    else
      render "edit"
    end
  end

  # /chapters/1 DELETE
  def destroy
    @chapter.destroy
    redirect_to action: "index"
  end

  private

  def find_genre
    @genre = Genre.find(params[:genre_id])
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_chapter
    @chapter = Chapter.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:name, :text)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :find_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  # /genres/1 GET
  def show
  end

  # /genres/new GET
  def new
    @genre = Genre.new
  end

  # /genres/1/edit GET
  def edit
  end

  # /genres POST
  def create
    @genre = Genre.create(genre_params)
    if @genre.errors.empty?
      redirect_to genre_path(@genre)
    else
      render "new"
    end
  end

  # /genres/1 PUT
  def update
    @genre.update_attributes(genre_params)
    if @genre.errors.empty?
      redirect_to genre_path(@genre)
    else
      render "edit"
    end
  end

  # /genres/1 DELETE
  def destroy
    @genre.destroy
    redirect_to action: "index"
  end

  private

  def find_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/audio_books/_form.html.slim
.col-md-3.row
  .col-md-3 = f.label :name
  .col-md-9 = f.text_field :name, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :floor
  .col-md-9 = f.text_field :floor, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :quantity
  .col-md-9 = f.text_field :quantity, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :available
  .col-md-9 = f.text_field :available, class: 'form-control'

app/views/audio_books/edit.html.slim
h1 Edit audio_book
= form_for([@genre, @audio_book]) do |f|
  = render partial: "form", locals: { f: f }
  .col-md-3.row = f.submit 'Save book', class: 'btn btn-success w-100'
p = link_to "Back", genre_audio_books_path

app/views/audio_books/index.html.slim
ul
  h1 = "#{@genre.name} audio books:"
  - if @audio_books.present?
    li
      h5 = "On the #{@audio_books.first.floor}th floor you can find these audio books."
    p
      li
        h5 = "These audio books with #{@audio_books.first.genre_id}th Genre_id"
table
  tr
    th Name
    th Quantity
    th Available
    th
    th
  - @audio_books.each do |book|
    tr
      td = link_to "#{book.name}", genre_audio_book_path(book.genre_id, book.id)
      td = book.quantity
      td = book.available
      td = link_to "Delete", genre_audio_book_path(@genre, book.id), method: :delete, data: { confirm: "Are you sure, remove?" }
      td = link_to "Edit", edit_genre_audio_book_path(@genre, book.id)
p
p #{link_to "Go to all categories of genres", genres_path(@genre)} or you can  #{link_to "Create a new audio book",  new_genre_audio_book_path(@genre, @books)}

app/views/audio_books/new.html.slim
h1 Create new audio book
= form_for([@genre, @audio_book]) do |f|
  = render partial: "form", locals: { f: f }
  .col-md-3.row = f.submit 'Create book', class: 'btn btn-success w-100'
p = link_to "Back", genre_audio_books_path

app/views/audio_books/show.html.slim
h1 = @audio_book.name

ul
  li = "Floor: #{@audio_book.floor}"
  - if @audio_book.quantity
    li = "Quantity: #{@audio_book.quantity} units"
    - if @audio_book.available
      li = "Available #{@audio_book.available}"
p = link_to "Return to all audio books of this genre", genre_audio_books_path

app/views/books/_form.html.slim
.col-md-3.row
  .col-md-3 = f.label :image
  .col-md-9 = f.file_field :image, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :name
  .col-md-9 = f.text_field :name, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :floor
  .col-md-9 = f.text_field :floor, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :quantity
  .col-md-9 = f.text_field :quantity, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :available
  .col-md-9 = f.text_field :available, class: 'form-control'

app/views/books/edit.html.slim
h1 Edit book
= form_for [@genre, @book], html: { multipart: true } do |f|
  = render partial: "form", locals: { f: f }
  .col-md-3.row = f.submit 'Save book', class: 'btn btn-success w-100'
p = link_to "Back", genre_books_path

app/views/books/index.html.slim
ul
  h1 = "#{@genre.name} books:"
  - if @books.present?
    li
      h5 = "You can find these books on the #{@books.first.floor}th floor."
    p
    li
      h5 = "Total #{@genre.books.map{ |x| x.quantity.present? ? x.quantity : 0 }.sum}th books of this genre."
    p
     li
       h5 = "These books with #{@books.first.genre_id}th Genre_id"

table
  tr
    th Image
    th Name
    th Quantity
    th Available
    th
    th Rating
    th
    th Chapters
  - @books.each do |book|
    tr
      - if book.image.present?
        td = link_to (image_tag (book.image.url(:thumb)), :style => "width: 50px; height: 70px; margin-bottom: 5px"), genre_book_path(book.genre_id, book.id)
      - else
        td = link_to image_tag("no_image.jpg", :style => "width: 50px; height: 70px; margin-bottom: 5px"), genre_book_path(book.genre_id, book.id)
      td = link_to "#{book.name}", genre_book_path(book.genre_id, book.id)
      td = book.quantity
      td = book.available
      td = link_to "Delete", genre_book_path(@genre, book.id), method: :delete, data: { confirm: "Are you sure, remove?" }
      td   #{book.votes_count}, #{link_to "+", upvote_genre_book_path(book.genre_id, book.id)}
      td = link_to "Edit", edit_genre_book_path(@genre, book.id)
      td = link_to "Lists", genre_book_chapters_path(@genre, book.id, @chapter)
p
p #{link_to "Go to all categories of genres", genres_path(@genre)} or you can  #{link_to "Create a new book",  new_genre_book_path(@genre, @books)}

app/views/books/new.html.slim
h1 Create new book
= form_for [@genre, @book], html: { multipart: true } do |f|
  = render partial: "form", locals: {f: f}
  .col-md-3.row = f.submit 'Create book', class: 'btn btn-success w-100'
p = link_to "Back", genre_books_path

app/views/books/show.html.slim
h1 = @book.name
ul
  li = "Floor: #{@book.floor}"
  - if @book.quantity
    li = "Quantity: #{@book.quantity} units"
  - if @book.available
    li = "Available #{@book.available}"
- if @book.image
  = image_tag @book.image.url(:medium), :style => "width: 200px; height: 250px"
p #{link_to "Return to all books of this genre", genre_books_path} or #{link_to "Edit", edit_genre_book_path}

app/views/chapters/_form.html.slim
.col-md-3.row
  .col-md-3 = f.label :name
  .col-md-9 = f.text_field :name, class: 'form-control'
.col-md-3.row
  .col-md-3 = f.label :text
  .col-md-9 = f.text_area :text, class: 'form-control'

app/views/chapters/edit.html.slim
h1 Edit chapter
= form_for([@genre, @book, @chapter]) do |f|
  = render partial: "form", locals: {f: f}
  .col-md-3.row = f.submit 'Save chapter', class: 'btn btn-success w-100'
p = link_to "Back", genre_book_chapters_path

app/views/chapters/index.html.slim
ul
  h1 = @book.name
  /h3  = "This book with name \"#{@book.name}\" has next chapters:"
h3  = "This book contains the following chapters:"
table
  tr
    th Name
    th
  - @chapters.each do |chapter|
    tr
      td = link_to "#{chapter.name}", genre_book_chapter_path(@book.genre_id, @book.id, chapter.id)
      td = link_to "Edit",  edit_genre_book_chapter_path(@genre, @book.id, chapter.id)
p
p  #{link_to "Back", genre_books_path(@genre)} or #{link_to "Create new chapter", new_genre_book_chapter_path}

app/views/chapters/new.html.slim
h1 New chapter
= form_for([@genre, @book, @chapter]) do |f|
  = render partial: "form", locals: {f: f}
  .col-md-3.row = f.submit 'Create chapter', class: 'btn btn-success w-100'
p = link_to "Back", genre_book_chapters_path

app/views/chapters/show.html.slim
h1 = @chapter.name
h3 = "Contains the following text:"
p = @chapter.text
p
p  #{link_to "Back to the chapters of this book.", genre_book_chapters_path} or #{link_to "Edit", edit_genre_book_chapter_path}

app/views/genres/_form.html.slim
.col-md-3.row
  .col-md-3 = f.label :name
  .col-md-9 = f.text_field :name, class: 'form-control'

app/views/genres/edit.html.slim
h1 Edit genre
= form_for(@genre) do |f|
  = render partial: "form", locals: {f: f}
  .col-md-3.row = f.submit 'Save genre', class: 'btn btn-success w-100'
p = link_to "Back", genre_path

app/views/genres/index.html.slim
- if user_signed_in?
  span Hello,
  = current_user.email
  = link_to 'Logout', destroy_user_session_path, :method => :delete
- else
   = link_to 'Login', new_user_session_path
   br
   = link_to 'Sign up', new_user_registration_path

h3 Category genres
- if @genres.empty?
    b No genres in library
- else

table
  tr
    th Genre name
    th
    th
    th
    th
  - @genres.each do |genre|
    tr
      td = genre.name
      td  #{link_to "Books", genre_books_path(genre)}
      td  #{link_to "Audiobooks", genre_audio_books_path(genre)}
      td = link_to "Edit", edit_genre_path(genre.id)
      td = link_to "Delete", genre_path(genre.id), method: :delete, data: {confirm: "Are you sure, remove?"}
p #{link_to "Create a new genre",  new_genre_path(@genre)}

app/views/genres/new.html.slim
h1 Create new genre
= form_for @genre do |f|
  = render partial: "form", locals: {f: f}
  .col-md-3.row = f.submit 'Create genre', class: 'btn btn-success w-100'
p = link_to "Back", genres_path

app/views/genres/show.html.slim
h1 = @genre.name

ul
  li = @genre.name
  - if @genre.category
    li = @genre.category
p = link_to "Return to all genres", genres_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <!--<p class="alert"><%= alert %></p>-->

    <%= yield %>
  </body>
</html>